# General configuration
homeassistant:
  elevation: !secret home_elevation
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  name: !secret home_name
  time_zone: America/New_York
  unit_system: imperial

# Base configuration
automation: !include_dir_merge_list automations
cloud:
config:
discovery:
frontend:
history:
ios:
logbook:
mobile_app:
recorder:
script: !include_dir_merge_named scripts
sun:
system_health:
updater:

# Integrations
august: !include integrations/august.yaml
ecobee: !include integrations/ecobee.yaml
group: !include groups.yaml
homekit: !include integrations/homekit.yaml
light: !include integrations/light.yaml
scene: !include scenes.yaml
rachio: !include integrations/rachio.yaml
wiz: !include integrations/wiz.yaml
