version: "3"
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - .:/config
    environment:
      - TZ=America/New_York
    restart: always
    network_mode: host
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
