- alias: Turn on lights at sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: group.outdoor_lights
    data:
      # 900 seconds = 15 minutes
      transition: 900

- alias: Turn off lights at sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: group.outdoor_lights
    data:
      # 900 seconds = 15 minutes
      transition: 900
