- alias: Turn on lights at sunset
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    entity_id: light.post_lamp
    data:
      transition: 0
      brightness: 40
      color_temp: 344

- alias: Turn off lights at sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
    service: light.turn_off
    entity_id: light.post_lamp
    data:
      transition: 0
