- alias: Sprinklers are on, turn on the pump
  trigger:
    - platform: state
      entity_id:
        - switch.front
        - switch.front_yard_east
        - switch.front_yard_west
        - switch.backyard
        - switch.backyard_2
        - switch.back_yard_flower
        - switch.back_yard_flower_2
        - switch.backyard_center
      from: "off"
      to: "on"
  action:
    - service: notify.notify
      data_template:
        title: "Sprinklers are on"
        message: "Turn on the pump!"

- alias: Sprinklers are off, turn off the pump
  trigger:
    - platform: state
      entity_id:
        - switch.front
        - switch.front_yard_east
        - switch.front_yard_west
        - switch.backyard
        - switch.backyard_2
        - switch.back_yard_flower
        - switch.back_yard_flower_2
        - switch.backyard_center
      from: "on"
      to: "off"
  action:
    - service: notify.notify
      data_template:
        title: "Sprinklers are off"
        message: "Turn off the pump!"
